#!/usr/bin/env ruby

class Repoman
  VERSION = '0.0.1'

  attr_reader :options

  def initialize(arguments)
    @arguments = arguments

    parse_options

    perform
  end

  def perform
    estimate_color = '#333333'
    estimate_labels = []
    5.times do |i|
      estimate_labels << "#{i+1} estimate"
    end

    actual_color = '#bfe5bf'
    actual_labels = []
    5.times do |i|
      actual_labels << "#{i+1} actual"
    end

    estimate_labels.each do |l|
      `ghi label \"#{l}\" -c \"#{estimate_color}\" -- \"#{@organization_repository}\"`
    end

    actual_labels.each do |l|
      `ghi label \"#{l}\" -c \"#{actual_color}\" -- \"#{@organization_repository}\"`
    end
  end

protected

  def parse_options
    require 'optparse'

    @options = {}
    optparser = OptionParser.new do |opts|
      opts.banner = "Usage: repoman <organization/repository> [options]"
      opts.separator ""
      opts.separator "Specific options:"

      # opts.on("-l", "--label", "Add predefined labels to repository") do |l|
      #   options[:label] = l
      # end

      opts.on_tail("-h", "--help", "Prints this help") do
        puts opts
        exit 0
      end

      opts.on_tail("-v", "--version", "Show version") do
        puts VERSION
        exit 0
      end
    end

    optparser.parse!(@arguments)

    if ARGV.empty?
      puts optparser
      exit 1
    else
      @organization_repository = ARGV[0]
    end
  end
end

Repoman.new(ARGV)
